# Generated by Django 4.1.7 on 2023-03-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_in', models.CharField(max_length=250, verbose_name='Логин')),
                ('password', models.CharField(max_length=250, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Данные пользователя',
            },
        ),
    ]
